spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tomatomall?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

alipay:
  app-id: 2021000148632792
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCrr4So1vobMexJ1hFvg1A66OiH26cYQuxbl6SGd7m/613bcIhAHUka1QqdDYxLTXrsJ923mUYhCKZjLe1n7KMsezH/yJNQwh1JZlCKcsPubbI3WUxxrgp7ETrOJ6d4gKAH3crelOmQgYkp52arHLFqVT4OsuoLrVJA2vorQCAXHizqPxoHii6JT3EgDvbbMdwy/S6Gz0GuDWtmRZ32LOGaxc33nThtS6cMagqT0F62KRhOloKzWkmq2WUyH9TsZZyJvDiW/29n5o4vMJ7mRj55Qww6yRgcaWntrfsASlUempNwsX9a6KjXiJbxnjS3j2MoQVAdQmI4FIfISN2L7c1lAgMBAAECggEAUBdgTpeDM56VeVh458mdau3uVDqe9814j73tTaGasLJvJYiYtzgyO2c5PUztrs9lUbfDUfwZ4B016byqLLoS4RRTndyHBLyZhv1JA11Ik/juk61/4ORtFT5TbYrIMInoneLU2gMj9nrHbxn5JkgLZ+x+N8M1Nd9UKNc+r2CJ195AhBK+ZF2JmtC9jfUhYPVGKAY279h56LbyNyjp18gROlICEqVGyoGftiy6xlIhjjA486mp8i1NSwzWBDl1cg2CHKE3aV32b7We2yPNqB7zKZPidCxVFFAv2rrKv6nDjVUdsQ+58WC46QcQBhMIFIbOBP01hWHbWEbSGMd7+bSuIQKBgQD3y0WW5lM5Ou7S+cMohbLml8JVIwpfwLo93yoTmbmIStlltEsyLHTqFe3pN0Ssrs6raxlp0bZlY+ylyyNY5Wh1e02NB/D1qUZc0iNCkgAmdmZzPdB3Y21gRzTaDAmDP4rxdC93peC5Aww3raZevhV5gyF+D6i9H6tTtyAnVdilOQKBgQCxXwVIBV+rgifXz7WcBpzvanoRlUcMkjk4i9iJV5YdeyL5M3maEhycwqqlHdaL2gnJzylIYG2cg5jt6oDYeUcfLylDPxiGeZYqRfHHxv4hYo1zs3ASgNr6ZQeU1pLV4aJtOVzAbpAx3WDsdwue8r62XBKlF2TWDbMyLZCrapY1jQKBgDy+xiaB/DDxc46gz+jlLcA9v9QjLO3gT0fPp376lnME9lpqYmzAXUDtc09SzzEOAXggXzCDypT8dA0IyXeHdZ4nRhGmurleb/NdSGuPYx4KtH7Xzn0WEMAjdJ9niAV21FbwxposPfTc/GfB2CEttBH/xXwj1pfWZae2ItnBv8RxAoGBAJqAebo9rBNaodg0Py7097j5F/G/BY+mw59E+c7Q85skitdmBlO12SSX0UtZDWzu9b3L7Vr1XCWM4CbGMYvfQJuiWiAQkw14Vdzm5nAuH2n3Td3t/P6xLY4VeSAmNOuHyxO3dtrMtGArRWVVYVMIgiWZWEhkc1qdvm1EEZOvmb51AoGAB28lUMssMuHV9qu0GoSbGBSk0sMk8euNJLJuqVp+Kec1qZyId1q7nJZqXiGO/vsbpbX7M/BFnh2ZUgXbqaWz6Elg/rB9z+4zYKf9QaXrrMpLujge1srHTZ7N8qKHlarWG3pKGmBTMoNt6wfR5TGidqumGHKFoRuusuuWN2yTTM8=
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnfLMfCF2BU22Ij7+yqsQrmRNLDGNPTVoSTjznO3HARLq8uqXryqS/jk6PADLNAmSoAubHlDNmWsyKIREtYuW6Ft+2ViZ09wH1XPMF00Y+Ztl15ZV+vxQ8JuEybL2V4Gec8LK5mqK/D/ufqFSDu1cpkURrBx59fBxvzKRYYbI1lopEYTcms3/bQgOhl0clPaTEKbkccgJeEp59C/vCnazBdV18adPco9i9C8+MEpJ8IYSEgzT/6AlVvOSmmk3gQCxlBZXjmWWc2nhyxCTGM8Tc9Cta79fF9CiLZBemd0svuW1VMOu5ZHW5F/M5caK2+hbvQiuuSYbRJIOy5AGbFqSvwIDAQAB
  server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  charset: utf-8
  sign-type: RSA2
  notify-url: http://q2e6b85e.natappfree.cc/api/orders/notify
  return-url:  http://q2e6b85e.natappfree.cc/api/orders/returnUrl

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

